; ================================================================
; PlatformIO Project Configuration File
; Audio-to-Vibration AI — Alat Bantu Tuna Rungu
;
; config.h ada di lib/AppConfig/config.h — otomatis ditemukan
; oleh semua library dan src/ tanpa perlu flag -I tambahan.
; ================================================================

; ----------------------------------------------------------------
; Shared defaults
; ----------------------------------------------------------------
[env]
platform      = espressif32
framework     = arduino
monitor_speed = 115200

; ----------------------------------------------------------------
; ENV 1 — Aplikasi utama | board: XIAO ESP32-S3
; ----------------------------------------------------------------
[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3

build_src_filter =
    +<*>
    -<SampleGetter/>

board_build.mcu = esp32s3
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv  ; Untuk kapasitas flash ekstra (16MB)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -I ${PROJECT_DIR}/src
    -Wno-deprecated-declarations

lib_ignore = Arduino_LSM9DS1, PDM, Arduino_OV767X

; ----------------------------------------------------------------
; ENV 2 — Ambil data training | board: XIAO ESP32-S3
; ----------------------------------------------------------------
[env:seeed_xiao_esp32s3_sampler]
board = seeed_xiao_esp32s3

build_src_filter =
    +<*>
    -<MainApp/>

build_flags =
    -DBOARD_HAS_PSRAM
    -I ${PROJECT_DIR}/src
    -DSAMPLER_MODE
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_ignore = SoundClassifier, VibrationMotor

board_build.mcu = esp32s3
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv  ; Untuk kapasitas flash ekstra (16MB)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio


[env:esp32s3_sampler]
board = esp32-s3-devkitc-1

build_src_filter =
    +<*>
    -<MainApp/>

build_flags =
    -DBOARD_HAS_PSRAM
    -I ${PROJECT_DIR}/src
    -DSAMPLER_MODE
    -DGENERIC_ESP32S3
lib_ignore = SoundClassifier, VibrationMotor

board_build.partitions = huge_app.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
