/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 30.06.2026 18:14:03

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0034620098304003477, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -379, 657, -413, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00031156232580542564, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  38, -15, 10, 1, -24, -11, 50, -14, -12, 9, 19, -8, 61, 0, 14, -6, 4, -39, -6, 9, -35, -6, 42, -5, -9, -13, 22, 1, 5, -8, 22, -31, 0, -10, -2, -8, -11, -23, -17, 8, -10, -11, 13, 22, 28, -14, -5, -16, 5, -10, -3, -25, -14, -20, 1, -1, 1, -15, 12, 13, 5, 10, -10, -9, 17, -24, -13, -10, -21, -6, 9, -15, -9, 0, -11, 29, 1, 33, 19, -21, 5, -19, 20, 0, 25, -10, 15, -5, -8, 9, -3, 12, 0, 57, 30, -24, 11, -41, 14, 27, 47, 15, 12, 26, 10, -1, 12, 19, 19, 51, 8, -1, 16, -14, 9, 8, 49, 10, -4, 24, 26, 2, 18, 13, 4, 38, 12, -12, 8, -27, 11, 22, 60, -6, 4, 15, 25, -1, 20, 33, 2, 7, -11, 11, -8, -2, 5, -8, 46, -4, 19, 3, 4, -1, 5, 26, 31, 0, -1, 3, 24, -29, -6, 3, 9, -7, 5, 3, 6, 8, -3, 19, 17, 2, 18, -9, -5, -18, 22, -3, -6, -15, 7, -3, 9, 27, 4, 22, -8, -7, 11, -3, 8, -12, -17, -17, -21, -10, 3, 11, 8, 37, 9, 11, 6, -11, 18, -19, -6, -19, -20, 26, 17, -21, -18, 1, 46, 16, 6, 26, -10, -27, 0, -31, -11, -19, -4, 21, 14, -11, 7, 3, 29, 23, -1, 10, 3, 15, -9, -24, 4, -23, -19, 27, 9, -25, 3, 17, 4, 2, 6, 2, 41, -7, -3, -29, -4, -31, 6, 27, -9, -23, 15, 13, -2, 17, 36, 1, 46, -25, -12, -20, -8, -35, 19, 35, -28, -24, 38, 5, 1, -2, 0, 29, 34, -5, -10, -3, -11, -19, 26, -9, -35, -27, 28, 4, 10, -2, 6, 43, 42, 12, -1, 9, -14, -21, 42, -17, -2, -2, 3, 1, -1, 20, -6, 32, 12, 41, -6, 19, 24, -17, 19, 13, -19, 3, -6, 11, 3, -5, -1, 22, 13, -2, 2, -3, -3, -20, -22, 15, -51, -17, 37, -4, 16, -3, -3, 24, 28, 0, 14, -48, -7, -20, 7, -18, -4, -8, 14, 5, 4, 0, 0, 30, -1, 27, 1, 7, -6, -12, 45, 17, 39, 25, -7, 17, 11, 18, -7, 57, -16, 66, -6, 32, 5, -9, 14, 20, -43, -11, 5, 0, 6, 11, 12, -10, 25, 41, 3, 0, 
  23, -6, -46, -12, -22, -37, 6, -47, -22, -23, -28, -7, -31, -53, 24, -72, 30, 24, -55, 2, -22, -39, 19, -47, -22, -17, -18, -54, -21, -26, 62, -81, 73, -28, -62, 29, -26, -44, 43, -35, -17, -18, -19, -75, -19, -46, 80, -94, 49, -23, -47, 45, -40, -34, 41, -30, -17, -16, 0, -64, 24, -50, 58, -91, 40, 11, -15, 19, -27, -27, 69, -21, -16, -12, 6, -26, 17, -60, 31, -44, -11, -15, -22, -15, -25, -27, 24, -27, -15, -17, -17, -14, -15, -55, 2, -25, -36, 59, -5, -39, -50, -22, -41, -38, -28, -27, -44, 1, -47, -53, -23, 12, -25, 9, -6, -33, -47, -26, -19, -39, -31, -21, -42, -25, -34, -75, 0, -5, -6, 21, -35, -33, -76, -30, -11, -58, -30, -25, -35, -32, -26, -67, 68, -18, 5, -7, -45, 2, -53, -36, 4, -50, -30, -24, -38, -60, -46, -71, 44, -66, 6, 6, -43, 4, -2, -22, 10, -34, -32, -23, -31, -46, -23, -67, 45, -60, 28, -7, -30, 15, 11, -13, 12, -14, -27, -25, -14, -44, -20, -53, 22, -40, 27, -13, -29, 44, -37, -32, 23, -12, -31, -31, 2, -31, 9, -72, 55, -43, 48, -29, -32, -20, -41, -35, 40, -41, -29, -19, -9, -45, 12, -62, 44, -37, -1, 15, -24, -26, -24, -23, 31, -40, -25, -27, -29, -20, -23, -85, 55, -30, -8, 18, -2, -34, -11, -9, 1, -27, -39, -35, -40, 26, -39, -40, 15, 6, 35, 7, -10, -16, -26, -18, -10, -35, -32, -30, -48, 17, -51, -42, 67, 11, 18, 29, -27, -43, -25, -20, -10, -59, -29, -22, -31, -39, -32, -55, 30, -45, 41, -8, -38, 27, -67, -24, -10, -39, -30, -33, -22, -60, -41, -82, 40, -55, 44, -3, -46, 47, -52, -33, 43, -33, -15, -17, 8, -47, 7, -89, 26, -68, 19, 6, -37, 2, -14, -28, 57, -28, -14, -12, 0, -60, 9, -78, 25, -54, 7, -9, -18, -9, -26, -33, -1, -18, -25, -22, -17, -30, -24, -79, 36, -29, 15, -12, -35, 36, -68, -33, 12, -34, -25, -20, -11, -37, 3, -87, 42, -54, 1, -24, -50, -6, -91, -51, 17, -48, -21, -23, -12, -47, 11, -96, 53, -79, -14, -16, -31, -12, -66, -41, 4, -44, -29, -26, -28, -1, -18, -104, 26, -32, 
  -36, 22, 49, -11, 21, 15, -42, 9, 19, 8, 8, 2, -29, 33, -28, 99, -28, 35, 33, -3, 75, 64, -31, 7, -5, 20, -6, 59, -6, 0, -35, 116, -34, 32, 41, -14, 37, 46, -23, 27, 2, -5, -8, 54, -6, 23, -34, 97, -26, 10, 18, -15, 81, 12, -34, 14, 0, 16, -3, 34, -22, 9, -36, 116, -20, 52, 14, 4, 61, 9, -39, 21, -7, -4, -21, -1, -17, 14, -40, 47, -22, 15, 11, 0, -8, 1, -30, 10, 0, 18, -10, -8, 6, -7, -27, 58, -14, 8, -12, 13, -28, 17, -7, -6, 10, -6, -10, -22, -2, -12, -14, 13, -19, 0, -4, -7, -22, 10, 1, -5, 2, -11, -1, -12, -8, -7, -23, -13, -11, 12, -9, -5, 27, -3, -12, -7, -11, -9, -10, -7, 15, 22, -23, -19, -20, 4, 28, 11, -3, 12, -12, -8, -9, 5, 10, 20, -4, 37, -28, 44, -14, 40, 25, -2, -25, 23, -15, -4, 3, -13, -2, 28, -5, 17, -33, 80, -13, 3, 14, -7, -18, 1, -18, 10, -11, -12, -10, 11, 3, 29, -18, 41, -13, 20, 28, -13, 105, 31, -15, 16, -5, -5, -10, 12, -9, 42, -35, 51, -28, 13, 38, -13, 21, 44, -26, 1, -9, -13, -16, 10, 2, 66, -29, 68, -20, 9, 20, -3, -11, 12, -23, -7, 5, -8, 13, 18, -3, 39, -28, 59, -15, 37, -8, -12, 1, 21, -15, -9, 11, 11, 4, -11, -2, 22, -24, 26, -20, 19, -3, -7, 41, 33, -24, 5, -3, 10, -11, -11, -10, 24, -19, -2, -21, 15, -2, -24, 44, 27, -29, -6, -7, -3, -1, -19, -15, 30, -25, 53, -24, 29, -5, -23, 69, 7, -32, 36, -5, -7, -9, -21, -24, 59, -29, 64, -14, 7, -16, -16, 15, 30, -25, 34, 5, -7, -21, -16, -24, 13, -18, 48, -23, 23, 6, -19, 33, 3, -31, 18, -4, 7, -15, 4, -9, 33, -23, 71, -16, 18, 18, -10, 119, 22, -31, 31, -8, -7, -3, 1, -4, 41, -24, 127, -18, 31, 12, -18, 115, 35, -23, 4, -11, -9, -5, -11, -6, 25, -32, 29, -11, 44, 1, -21, 27, 18, -21, 13, -6, -6, -13, -4, -17, -6, -19, 35, -26, 19, -4, -18, 105, 5, -24, -3, -11, -1, -16, -6, -6, 20, -15, 34, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.00791160948574543, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { 281, 941, 24, 571, 83, 21, 59, -77, -2920, -2645, -1285, 1083, -1019, -276, 503, 112, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00014371023280546069, 0.00014933511556591839, 0.00029716198332607746, 0.00017047922301571816, 0.00015645097300875932, 0.00018543179612606764, 0.00015828985488042235, 0.00029066734714433551, 6.3851766753941774e-05, 7.1573762397747487e-05, 0.0001269385393243283, 0.00021174839639570564, 0.00016762045561335981, 0.00021674047457054257, 0.00012026421609334648, 0.00031978872721083462, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 48,-23,56,13,-80,-8,32,-17, 24,-43,13,-4,-107,-7,72,-40, 52,-31,24,6,-127,-14,81,-22, 
  /* [1][0][][] */ -13,127,-21,-5,-38,-48,-38,16, -19,100,-23,-16,-11,-3,-12,17, 53,101,-11,-27,-18,-46,-25,-8, 
  /* [2][0][][] */ -13,23,-4,0,127,-2,-23,24, -8,22,9,3,122,-4,-9,32, -19,17,8,-4,95,2,9,21, 
  /* [3][0][][] */ -17,-35,32,0,-56,2,3,-1, -4,-45,8,27,-68,-6,40,-8, 0,-34,2,1,-26,-14,127,-3, 
  /* [4][0][][] */ -28,1,-29,-8,97,43,-15,34, -30,29,-22,-15,115,82,-14,13, -14,127,7,-19,106,106,-46,38, 
  /* [5][0][][] */ -36,59,12,15,125,-5,-4,40, -35,54,-1,-4,117,31,-3,5, -36,64,11,9,127,14,-11,31, 
  /* [6][0][][] */ 40,-61,14,18,-59,-2,127,-15, 35,-64,40,-11,-48,-9,82,-8, 26,-73,6,23,-58,7,28,-28, 
  /* [7][0][][] */ -14,22,-5,-2,67,59,2,30, -5,22,0,21,101,51,-7,31, -8,1,-15,4,127,45,7,29, 
  /* [8][0][][] */ -53,2,125,127,-53,16,60,103, -63,-6,26,120,-67,-4,23,124, -57,-55,59,86,-45,57,21,46, 
  /* [9][0][][] */ -30,2,50,115,-5,-30,46,91, -59,-64,56,84,-23,-15,57,60, -39,-10,81,127,-61,15,-11,109, 
  /* [10][0][][] */ -28,2,15,24,-91,-36,127,-4, -37,8,28,24,-99,-29,70,24, -11,-1,17,69,-105,5,69,55, 
  /* [11][0][][] */ -21,-25,-21,5,127,-9,-35,13, -16,-36,-7,-2,117,-17,-25,26, -14,-31,-19,6,61,-16,-31,17, 
  /* [12][0][][] */ -31,1,-11,42,-65,-19,127,-4, -16,-13,-6,7,-65,-10,53,-11, -5,8,31,15,-65,-30,62,6, 
  /* [13][0][][] */ -49,23,21,5,44,-14,-12,-26, -51,54,25,12,81,-13,-15,-10, -58,68,67,18,127,-6,-3,19, 
  /* [14][0][][] */ 83,-27,58,0,-109,-2,22,-29, 34,-10,66,13,-123,-24,49,-28, 95,-45,27,48,-127,-37,34,-32, 
  /* [15][0][][] */ -6,45,-4,-5,127,-9,-10,29, -9,17,2,-7,106,-13,-2,17, -13,5,2,-12,77,-11,-7,12, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.010794481262564659, 0.011216981336474419, 0.022320674732327461, 0.01280517503619194, 0.011751473881304264, 0.013928305357694626, 0.011889597401022911, 0.021832844242453575, 0.0047960863448679447, 0.0053761070594191551, 0.0095347119495272636, 0.015905018895864487, 0.012590444646775723, 0.016279987990856171, 0.00903338473290205, 0.024020234122872353, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 1521, 3106, 3344, -2955, -170, -205, -3929, -44, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 7.1500202466268092e-05, 2.1579659005510621e-05, 3.4515251172706485e-05, 2.5833898689597845e-05, 1.7587020920473151e-05, 3.749417737708427e-05, 2.1983763872412965e-05, 2.4832976123434491e-05, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -2,4,20,103,7,-6,-17,-18,-16,-23,-34,-15,4,15,-12,1,-25,12,3,-9,23,3,2,0,-3,18,-7,-17,-5,-12,-8,-8,-1,-11,-11,1,-2,2,0,20, -4,2,10,127,16,-6,-14,-14,-14,-23,-31,-5,-8,32,-5,2,-17,10,-2,6,-1,6,-4,-9,-14,13,-3,-12,-10,-17,-14,-10,-10,-16,-15,1,0,4,-2,17, 1,0,47,64,52,-5,-22,-17,-16,-20,-41,-15,2,11,-9,-1,-27,8,4,-8,18,-1,-5,-6,-7,10,-18,-10,-8,-12,-10,-16,-5,-12,-14,0,-4,8,4,21, 
  /* [1][0][][] */ -8,-11,-8,-49,-57,-43,-72,33,-4,96,-35,-43,45,-27,63,-8,4,33,101,33,-20,-24,-16,-48,9,-25,-29,-24,-26,6,-12,-37,-24,13,56,30,-36,-37,-38,-69, 8,-12,-41,-50,-54,-29,-43,26,-8,51,-40,-21,28,-39,-29,2,58,-4,23,-2,-19,4,-34,-49,-15,-17,-10,-33,-26,21,-27,-27,-25,27,37,3,-36,-33,-45,-75, 6,-27,-17,-71,-63,-40,-43,3,-20,102,-57,8,67,-33,1,-16,43,127,94,-11,-36,-8,-36,-27,41,54,-12,23,-25,-28,1,-34,-8,-27,17,25,-9,-26,-53,-37, 
  /* [2][0][][] */ 5,17,-4,67,104,8,55,5,-16,-35,49,29,13,2,-3,-13,11,-24,31,-4,-11,18,-19,-10,5,-18,-16,-29,-12,-29,-20,-5,-23,-19,-23,-27,9,-12,3,27, 12,9,11,38,122,36,60,-4,22,-48,54,16,-3,21,23,-13,-7,-23,27,3,-19,48,-18,-3,-10,16,-12,-18,-18,-26,-14,8,-21,-23,-41,-26,-12,11,-7,26, -1,-17,-12,28,127,5,76,29,19,-51,3,19,2,31,6,-10,-3,-24,40,-24,-14,41,-17,6,29,-24,4,-22,-1,5,9,-4,-3,-34,-21,-21,11,33,2,20, 
  /* [3][0][][] */ -29,-20,-30,-26,75,15,111,3,62,-72,-1,0,-10,10,5,-34,17,-14,18,-24,-17,44,-12,7,3,8,19,-22,25,-3,4,29,28,-9,-28,-9,-3,2,-9,58, -14,-13,-22,-14,67,52,127,-9,57,-43,-15,18,-15,-6,20,-44,19,-3,9,-14,-13,28,-26,11,-4,-31,16,-13,14,-16,24,57,22,-18,-50,-23,10,-8,47,31, 39,17,23,-4,101,94,109,-3,-5,-46,44,17,-20,13,-18,-28,-3,-12,4,-3,-42,35,-35,-6,-13,-14,30,15,35,-24,25,2,7,-17,-53,-19,10,-14,-2,34, 
  /* [4][0][][] */ 11,-19,4,-17,-91,-18,-25,-20,-99,17,-6,111,127,106,110,85,-38,-48,-64,-70,-46,-41,-1,24,-73,48,-6,14,63,-3,-20,17,-17,19,97,-30,-50,9,-46,-57, 56,33,44,-45,-59,-8,1,-26,-67,21,18,79,38,86,38,6,-38,-11,-32,-54,-42,-12,38,23,-61,113,6,-24,21,44,-26,52,-20,3,102,-4,-53,-18,-60,-70, 39,-9,-6,-41,-92,-29,-21,-37,-93,-4,6,104,126,108,35,6,-50,-42,-46,-53,-47,-31,6,-17,-72,5,-29,-24,5,30,9,-20,40,49,11,-9,-28,-15,-52,-104, 
  /* [5][0][][] */ 3,7,-8,-36,13,-11,-8,14,7,122,34,13,-14,-13,-23,-21,-24,-17,-21,26,37,-29,14,-4,-23,-22,1,-1,-15,29,-13,18,6,11,48,-3,-10,-17,2,-35, -16,-16,-8,-42,-4,-29,-31,-2,2,77,27,-14,-22,-15,-26,-22,-15,-22,0,38,63,-35,-3,22,-30,-3,-10,6,1,14,-4,0,-5,31,18,0,1,11,-12,-32, -1,-19,-9,-47,-11,-16,-17,4,17,127,69,0,-21,-10,-26,-19,0,-29,-21,-8,66,-15,-13,23,-22,-18,23,5,-2,-2,1,15,-1,-2,12,-13,-10,-18,-9,-21, 
  /* [6][0][][] */ -18,-14,-25,-20,-46,69,90,-30,-55,-85,-30,-12,-39,-15,5,-28,-17,-26,43,-37,-55,106,-31,27,1,23,91,39,23,-36,-10,11,62,-14,-36,-15,-28,16,-13,1, -29,-37,-10,2,-49,109,110,-24,-34,-56,-29,6,-51,-1,17,-29,-31,-55,62,-6,-71,21,-33,13,-21,75,32,66,2,-33,16,70,8,13,-36,-12,15,18,-14,3, -9,-16,-9,12,-32,54,127,-39,-33,-58,-35,-20,-39,-24,-11,-37,7,-38,51,-41,-73,27,-12,8,25,33,-6,8,-4,-19,-28,28,23,21,-28,-3,-24,-11,-28,7, 
  /* [7][0][][] */ -2,-17,12,-31,-5,-32,-46,19,-12,60,53,-25,39,-26,-13,23,28,127,-19,7,-10,-23,-22,-5,8,16,-14,15,35,46,-11,-14,24,52,39,-8,-20,-22,-16,-49, -5,0,3,-30,-22,-48,-37,12,-17,90,50,-29,3,-21,-28,-21,-3,20,-19,-15,-12,-30,-6,0,-14,7,-30,3,8,-10,-33,-19,15,17,63,-2,-31,-21,-38,-49, -8,-16,2,-32,-19,-36,-31,-4,-19,97,7,-4,-25,8,14,43,51,96,16,5,-8,-20,0,7,-22,68,-3,16,-7,26,4,22,-12,5,14,7,-41,-26,-15,-32, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.020652800798416138, 0.0062332749366760254, 0.009969715029001236, 0.0074621103703975677, 0.0050800032913684845, 0.010830176062881947, 0.0063500003889203072, 0.0071729943156242371, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.013313306495547295, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.039380397647619247, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 1.6463686227798462, } };
const TfArray<1, int> quant21_zero = { 1, { 33 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1041218_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1041218_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1041218_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1041218_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1041218_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
